#!/bin/csh -f
if ($#argv < 2 || $#argv > 3) then
	echo "Usage: $0 <host> <mountpoint> [installed-bin-directory]"
	exit 1;
endif
if ($#argv == 3) then
	set b = $3/smount
else
	set b = smount
endif
# nfs port
set nport = 2999
# efs port
set mport = 2997
set dir = $1":"/
echo $b -v -o soft,intr,port=$nport,mport=$mport,timeo=60,rsize=8192,wsize=8192 $dir $2
$b -v -o soft,intr,port=$nport,mport=$mport,timeo=60,rsize=8192,wsize=8192 $dir $2
if ($status) echo "To mount anything, you must be root and a Shore server must be running."
