/* --------------------------------------------------------------- */
/* -- Copyright (c) 1994, 1995 Computer Sciences Department,    -- */
/* -- University of Wisconsin-Madison, subject to the terms     -- */
/* -- and conditions given in the file COPYRIGHT.  All Rights   -- */
/* -- Reserved.                                                 -- */
/* --------------------------------------------------------------- */

/*
 *  $Header: /p/shore/shore_cvs/src/vas/server/replybuf.C,v 1.13 1995/07/14 19:50:13 nhall Exp $
 */
#include <copyright.h>
#define __malloc_h
#include <msg.h>
#include "nfs.h"
#include <errors.h>

// you may very well wonder why it takes a
// separate function to allocate this...
// well, it has to do  with the fact that
// the types in the unions are
// generated by rpcgen, and defined in msg.h, nfs.h
// but we do *not* want the rest of the vas
// code to include msg.h because it gets full
// class definitions for types from C++ include
// files, whereas msg.h is C definitions.

EXTERNC char *_svas_replybuf();

char *
_svas_replybuf(int i)
{
	char 	*reply_buf;
	int 	amt = sizeof(client_replybuf);

	if(amt < sizeof(nfs_replybuf))
		amt = sizeof(nfs_replybuf);

	reply_buf = new char[amt];
	if(reply_buf == NULL) {
		catastrophic( "Cannot create a reply buf ", 0);
	}
	memset(reply_buf,'\0',amt);
	return reply_buf;
}

